os:
  - linux
  - osx

language: 
  - cpp

# force updated ubuntu distribution with up-to-date gcc
dist: bionic

branches:
  - main
  - dev
  - travis-test

env:
  global:
  - PKGS_OSX="jack qt rt-audio"
  
addons:
  apt:
    update: true
    packages:
      - qt5-default
      - qttools5-dev-tools
      - libjack-dev 
      - librtaudio-dev

before_script:
  # manually install brew packages as addon: homebrew is broken in the default osx image
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then HOMEBREW_NO_AUTO_UPDATE=1 brew install $PKGS_OSX; fi
  # mac: workaround for homebrew qmake not being symlinked into $PATH
  # see https://stackoverflow.com/questions/48847505/why-cant-i-use-qmake-on-mac-after-installing-it
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export PATH="/usr/local/opt/qt/bin:$PATH"; fi

script: 
  # build executable
  - pushd src
  - ./build
  - popd
  # run tests
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./scripts/testsuite.py; fi
  
after_success:
  - echo "Success!"

after_failure:
  - echo "Something went wrong :("
